### ISSUE TITLE
Error invalid_collector_id

### ISSUE THREAD

**Issue by CesarMdz** [mateo2181/mercadopago-laravel#1]
Hola @mateo2181 antes que nada gracias por este aporte!

ya realice los paso que mencionas para instalarlo pero ahora me manda un error, que es invalid_collector_id
en el array que me devuelve bien esta info:

array:4 [▼
  "message" => "collector_id invalid"
  "error" => "invalid_collector_id"
  "status" => 400
  "cause" => null
]
y ese null en "cause" me da el error principal que es

Invalid argument supplied for foreach() y es por que en el array "cause" no trae nada, espero puedas ayudarme.

Saludos y gracias!

**Comment by mateo2181** [comment]
Hola @CesarMdz, si es el mismo error que me comentaste en el Issue dentro del repo de Bagisto, creo que la versión de la libreria de MP deberia solucionar el problema.

**Comment by CesarMdz** [comment]
hola amigo,ya instale la version 1.8.1 y ahora me da este error:`<img src="https://i.ibb.co/rH7dB5z/Sin-t-tulo.png" alt="Sin-t-tulo" border="0">

**Comment by CesarMdz** [comment]
Hola amigo ps no se porque me da ese error ya cambie la version de mercado y todo, como dato estoy trabajando con Bagisto pero me da este error:         

$preference = new MercadoPago\Preference();
.
.
."Trying to access array offset on value of type null"

**Comment by mateo2181** [comment]
podrias adjuntar la imagen con el error?

**Comment by CesarMdz** [comment]
hola si claro
Este es el error principal. 
<a href="https://ibb.co/3CCcBCw"><img src="https://i.ibb.co/FDDzgD9/Sin-t-tulo.png" alt="Sin-t-tulo" border="0"></a>

Pero me marca error en el MPController

<a href="https://ibb.co/YLRdy9M"><img src="https://i.ibb.co/yQfkYT1/Sin-t-tulo.png" alt="Sin-t-tulo" border="0"></a>

**Comment by CesarMdz** [comment]
Hola amigo, ahora me aparece este error no se si podrias ayudarme
<a href="https://ibb.co/7pYLL76"><img src="https://i.ibb.co/8xKttFS/Sin-t-tulo.png" alt="Sin-t-tulo" border="0"></a>

**Comment by CesarMdz** [comment]
> 
> 
> Hola amigo, ahora me aparece este error no se si podrias ayudarme
> [![Sin-t-tulo](https://camo.githubusercontent.com/70fd9a4aea2a3b962bfb938ed14a86fb88c7b122/68747470733a2f2f692e6962622e636f2f38784b747446532f53696e2d742d74756c6f2e706e67)](https://ibb.co/7pYLL76)

Como dato, baje a la version 1.8.1 pero me seguia tirando el error de $preference = new MercadoPago\preference();

despues volvi a instalar la version 2.0.0 pero en lugar de poner

   MercadoPago\SDK::setClientId(env("MP_CLIENT_ID"));
   MercadoPago\SDK::setClientSecret(env("MP_CLIENT_SECRET"));

lo cambie a 
 MercadoPago\SDK::setAccessToken("mi_access_token"); 

y ahora que  hice dd($preference) me da ese error, ya intente borrar  y reproducir el ejemplo de la documentacion oficial, pero aun me sigue dando un error: "The name of the following parameters is wrong"

**Comment by mateo2181** [comment]
disculpa que recien lo veo, no te respondi enseguida y se me olvidó. Ahi creo que el problema viene por los valores que les pasas a esas variables, back_urls son las rutas de retorno desde la Api de MP que vos definis para cada caso(exito, fallo y cancelacion) y los otros campos tambien tienen que tener valores definidos.

**Comment by CesarMdz** [comment]
Hola gracias, creo que andaba fallando el servicio de mercadopago, porque de un dia para otro ya no me marco error. 

Sigo tratando de enterder un poco más, pero tu código a sido de mucha ayuda, gracias
